---
name: Arduino CI

on: [push, pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Arduino-CI/action@stable-1.x
        env:
          USE_SUBDIR: Codigo1